# -*- coding: utf-8 -*-
"""EDA_Flower_Iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKZf9QguhZOgiJmTr5q-gZ_7b1xV2tWs
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('IRIS.csv')
df

print (df.shape)

print (df.columns)

df['species'].value_counts()

df.plot(kind="scatter", x='sepal_length',y='sepal_width')
plt.show()

sns.set_style('whitegrid')
sns.FacetGrid(df, hue='species') \
  .map(plt.scatter,"sepal_length","sepal_width") \
  .add_legend()
plt.show()

plt.close()
sns.set_style('whitegrid');
sns.pairplot(df,hue='species',size=3);
plt.show()

# iris_setosa = df.loc[df['species']=='setosa'];
# iris_virginica = df.loc[df['species']=='verginica'];
# iris_versicolor = df.loc[df['species']=='versicolor'];
# plt.plot(iris_setosa['petal_length'],np.zeros_like(iris_setosa['petal_length']))

sns.FacetGrid(df, hue="species") \
   .map(sns.distplot, 'petal_length') \
   .add_legend();
plt.show()

sns.FacetGrid(df, hue="species") \
   .map(sns.distplot, 'petal_width') \
   .add_legend();
plt.show()

sns.FacetGrid(df, hue="species") \
   .map(sns.distplot, 'sepal_width') \
   .add_legend();
plt.show()

sns.FacetGrid(df, hue="species") \
   .map(sns.distplot, 'sepal_length') \
   .add_legend();
plt.show()